version: '3.8'

services:

  web:
    build: .
    command: ./entrypoint.sh
    expose:
      - 6000
    ports:
      - "6000:6000"
    depends_on:
      - cloud-sql-proxy
    env_file:
      - ./.env
    logging:
      driver: gcplogs
      options:
        labels: environment,version
        env: GCP_LOG_LEVEL
    volumes:
      - /credentials:/credentials

networks:
  shared-network:
    name: shared_network
    external: true
