version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: devleague
    ports:
      - "5433:5433"
    volumes:
      - psql_data:/var/lib/postgresql/data
    command: -p 5433
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./:/workspace/devleague
volumes:
  psql_data:
