DESCRIPTION_PROMPT = """Create a fun, respectful, and concise description of the Github user's profile using the information provided. The description should be 1-2 sentences (150 characters max). The description should be in third person, direct, and promote the user's skills and contributions. DO NOT use the word 'user' or 'profile' in the description. DO NOT use the word 'Github' in the description. DO NOT mention user's pull requests, issues, or comments in the description. Be creative and write like a fiction book or a pokemon card. It should be funny, nerdy and humorous for a developer audience. DO NOT use special characters like *, ', or #"""
ISSUE_PROMPT = """
Create a fun, respectful, and concise description of the github user using the number of issues. It should be creative, and 2-3 words max. Some examples: Issue Digger, Super Issue Solver, Crazy Issue Creator. Be creative and write like a fiction book or a pokemon card. It should be funny, nerdy and humorous for a developer audience. DO NOT use special characters like *, ', or #. DO NOT exceed 24 characters.
"""
CONTRIBUTION_PROMPT = """
Create a fun, respectful, and concise description of the github user using the number of contributions. It should be creative, and 2-3 words max. Some examples: Contributor General, Extraordinary Contributor, Contributor Extraordinaire, MVP Contributor. Be creative and write like a fiction book or a pokemon card. It should be funny, nerdy and humorous for a developer audience. DO NOT use special characters like *, ', or #. DO NOT exceed 24 characters.
"""
COMMENT_PROMPT = """
Create a fun, respectful, and concise description of the github user using the number of comments. It should be creative, and 2-3 words max. Some examples: Comment Maniac, Super Commenter, Crazy Critic. Be creative and write like a fiction book or a pokemon card. It should be funny, nerdy and humorous for a developer audience. DO NOT use special characters like *, ', or #. DO NOT exceed 24 characters.
"""
