"""make github auth nullable

Revision ID: ac6fb51f81e6
Revises: 273bf1c90d21
Create Date: 2025-01-06 02:16:48.106728

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac6fb51f81e6"
down_revision: Union[str, None] = "273bf1c90d21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("github_auths", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "github_auths", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "github_auths", type_="foreignkey")
    op.drop_column("github_auths", "user_id")
    # ### end Alembic commands ###
