"""remove github auth relation

Revision ID: 19578f8ef588
Revises: 6ce72f3ddd27
Create Date: 2025-01-29 02:50:40.548543

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19578f8ef588"
down_revision: Union[str, None] = "6ce72f3ddd27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_github_auths_github_id", table_name="github_auths")
    op.drop_index("ix_github_auths_id", table_name="github_auths")
    op.drop_table("github_auths")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_auths",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("github_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("refresh_token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "token_expires_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="github_auths_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="github_auths_pkey"),
    )
    op.create_index("ix_github_auths_id", "github_auths", ["id"], unique=False)
    op.create_index(
        "ix_github_auths_github_id", "github_auths", ["github_id"], unique=True
    )
    # ### end Alembic commands ###
