"""add type column

Revision ID: aed90aa089c8
Revises: 9c24ff912d32
Create Date: 2025-01-08 02:12:41.390461

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aed90aa089c8"
down_revision: Union[str, None] = "9c24ff912d32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "type")
    # ### end Alembic commands ###
